# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir W:/Sonar.cache/wt [current_project]
set_property parent.project_path W:/Sonar.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files W:/Sonar.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_0/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_fir_compiler_0_0/design_1_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_cic_compiler_0_0/design_1_cic_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_0_1/design_1_fifo_generator_0_1/design_1_fifo_generator_0_1.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_0_1/design_1_fifo_generator_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_axis_switch_0_0/design_1_axis_switch_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_axis_switch_0_1/design_1_axis_switch_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all w:/Sonar.srcs/sources_1/bd/design_1/ip/design_1_dist_split_0/design_1_dist_split_0_ooc.xdc]
set_property used_in_implementation false [get_files -all W:/Sonar.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files W:/Sonar.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib -sv {
  W:/Sonar.srcs/sources_1/new/seg7.sv
  W:/Sonar.srcs/sources_1/new/sonar.sv
  W:/Sonar.srcs/sources_1/new/bcd.sv
  W:/Sonar.srcs/sources_1/new/seg_display.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc W:/Sonar.srcs/constrs_1/imports/Basys3_Master.xdc
set_property used_in_implementation false [get_files W:/Sonar.srcs/constrs_1/imports/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top sonar -part xc7a35tcpg236-1


write_checkpoint -force -noxdef sonar.dcp

catch { report_utilization -file sonar_utilization_synth.rpt -pb sonar_utilization_synth.pb }
